/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TreeIntersection.app.src.main.java.treeintersection;

import java.util.HashSet;

public class App {

    public static void main(String[] args) {

        Node tree1 = new Node(1);
        tree1.left = new Node(2);
        tree1.right = new Node(3);
        tree1.left.left = new Node(4);
        tree1.left.right = new Node(5);

        Node tree2 = new Node(2);
        tree2.left = new Node(4);
        tree2.right = new Node(6);
        tree2.left.left = new Node(8);
        tree2.left.right = new Node(5);

        HashSet<Integer> valuesInTree1 = new HashSet<>();
        TreeIntersection.populateHashSet(tree1, valuesInTree1);
        System.out.println("Values in tree1: " + valuesInTree1);

        HashSet<Integer> result = new HashSet<>();
        TreeIntersection.findIntersection(tree2, valuesInTree1, result);
        System.out.println("Intersection found in tree2: " + result);

        HashSet<Integer> intersection = TreeIntersection.treeIntersection(tree1, tree2);
        System.out.println("Final Intersection: " + intersection);
    }
}
