/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Graphs.app.src.main.java.graphs;

import java.util.Collection;

public class App {
    public static void main(String[] args) {
        Graph graph = new Graph();

        int vertexValue = graph.addVertex(1);
        System.out.println("Vertex added: " + vertexValue);

        graph.addVertex(2);
        graph.addEdge(1, 2, 5);
        System.out.println("Edge added between 1 and 2 with weight 5");

        Collection<Integer> vertices = graph.getVertices();
        System.out.println("All vertices: " + vertices);

        Collection<Graph.Edge> neighbors = graph.getNeighbors(1);
        System.out.println("Neighbors of vertex 1: " + neighbors);

        int graphSize = graph.size();
        System.out.println("Size of the graph: " + graphSize);

        Graph singleVertexGraph = new Graph();
        int singleVertex = singleVertexGraph.addVertex(1);
        singleVertexGraph.addEdge(1, 1, 3);
        System.out.println("Single vertex graph: " + singleVertexGraph.getVertices() +
                ", Edge: " + singleVertexGraph.getNeighbors(1));
    }
}
