/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StackAndQueue.lib.src.main.java.stackqueue;

import StackAndQueue.lib.src.main.java.stackqueue.queue.Queue;
import StackAndQueue.lib.src.main.java.stackqueue.stack.Stack;

public class Library {
    public static void main(String[] args) {
        Queue<Integer> q1 = new Queue<>();

        System.out.println("Queue: ");
        // testing the isEmpty method
        System.out.println("Is the queue list is empty??  " + q1.isEmpty());

        // testing peek on an empty queue
        q1.peek();

        // testing enqueue
        q1.enqueue(1);
        q1.enqueue(2);
        q1.enqueue(3);

        System.out.println("Queue after enqueue some numbers :");
        System.out.println(q1);

        // testing dequeue
        // here the queue FIFO, the first number will be removed which is 1
        q1.dequeue();

        System.out.println("Queue after dequeue :");
        System.out.println(q1);

        // testing peek
        System.out.println("now you can Peek: " + q1.peek());

        // here the output should not be empty now
        System.out.println("Is the queue list is empty??  " + q1.isEmpty());

        System.out.println("---");

        System.out.println("Stack :");

        Stack<Integer> s1 = new Stack<>();
        // testing the isEmpty method
        System.out.println("Is the stack list is empty??  " + s1.isEmpty());

        // testing peek on an empty stack
        s1.peek();

        // testing push
        s1.push(4);
        s1.push(5);
        s1.push(6);

        System.out.println("Stack after push some numbers :");
        System.out.println(s1);

        // testing pop
        // here the stack LIFO, the first number will be removed which is 6, 6 will be at fist cuz the push is happening in the top of the list
        s1.pop();

        System.out.println("Stack after the pop :");
        System.out.println(s1);

        // testing peek
        System.out.println("Peek : " + s1.peek());

        // here the output should not be empty now
        System.out.println("Is the satck list is empty??  " + s1.isEmpty());

    }
}
