/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SortingMovies.app.src.main.java.sortingmovies;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {

        Movie[] movies = {
                new Movie("harry potter and the order of the phoenix", 2007),
                new Movie("Rush Hour 2", 2001),
                new Movie("Mulan", 1998),
                new Movie("harry potter and the goblet of fire", 2005)
        };

        MovieSorter movieSorter = new MovieSorter();

        Arrays.sort(movies, movieSorter.getSortByRecentYear());
        System.out.println("Sorted by most recent year:");
        movieSorter.printMovies(movies);

        System.out.println("----");

        Arrays.sort(movies, movieSorter.getSortByTitleIgnoringPrefix());
        System.out.println("Sorted by title:");
        movieSorter.printMovies(movies);
    }
}
